# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1067, 678)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_8 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.resp_rate_label = QtWidgets.QLabel(self.splitter_8)
        self.resp_rate_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resp_rate_label.setObjectName("resp_rate_label")
        self.resp_rate_lcd = QtWidgets.QLCDNumber(self.splitter_8)
        self.resp_rate_lcd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resp_rate_lcd.setObjectName("resp_rate_lcd")
        self.resp_rate_slider = QtWidgets.QSlider(self.splitter_8)
        self.resp_rate_slider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resp_rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.resp_rate_slider.setObjectName("resp_rate_slider")
        self.gridLayout.addWidget(self.splitter_8, 7, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.plateau_press_label = QtWidgets.QLabel(self.splitter_3)
        self.plateau_press_label.setObjectName("plateau_press_label")
        self.plateau_press_lcd = QtWidgets.QLCDNumber(self.splitter_3)
        self.plateau_press_lcd.setObjectName("plateau_press_lcd")
        self.gridLayout.addWidget(self.splitter_3, 8, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.fio2_label = QtWidgets.QLabel(self.splitter_2)
        self.fio2_label.setObjectName("fio2_label")
        self.fio2_lcd = QtWidgets.QLCDNumber(self.splitter_2)
        self.fio2_lcd.setObjectName("fio2_lcd")
        self.fio2_slider = QtWidgets.QSlider(self.splitter_2)
        self.fio2_slider.setOrientation(QtCore.Qt.Horizontal)
        self.fio2_slider.setObjectName("fio2_slider")
        self.gridLayout.addWidget(self.splitter_2, 6, 0, 1, 1)
        self.splitter_9 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.tv_label = QtWidgets.QLabel(self.splitter_9)
        self.tv_label.setObjectName("tv_label")
        self.tv_lcd = QtWidgets.QLCDNumber(self.splitter_9)
        self.tv_lcd.setObjectName("tv_lcd")
        self.tv_slider = QtWidgets.QSlider(self.splitter_9)
        self.tv_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tv_slider.setObjectName("tv_slider")
        self.gridLayout.addWidget(self.splitter_9, 4, 0, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.ie_label = QtWidgets.QLabel(self.splitter_4)
        self.ie_label.setGeometry(QtCore.QRect(0, 0, 47, 16))
        self.ie_label.setObjectName("ie_label")
        self.ie_lcd = QtWidgets.QLCDNumber(self.splitter_4)
        self.ie_lcd.setObjectName("ie_lcd")
        self.ie_slider = QtWidgets.QSlider(self.splitter_4)
        self.ie_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ie_slider.setObjectName("ie_slider")
        self.gridLayout.addWidget(self.splitter_4, 5, 0, 1, 1)
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.mode_label = QtWidgets.QLabel(self.splitter_5)
        self.mode_label.setObjectName("mode_label")
        self.mode_button = QtWidgets.QPushButton(self.splitter_5)
        self.mode_button.setCheckable(True)
        self.mode_button.setObjectName("mode_button")
        self.gridLayout.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.splitter_6 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.peep_label = QtWidgets.QLabel(self.splitter_6)
        self.peep_label.setObjectName("peep_label")
        self.peep_lcd = QtWidgets.QLCDNumber(self.splitter_6)
        self.peep_lcd.setObjectName("peep_lcd")
        self.gridLayout.addWidget(self.splitter_6, 1, 0, 1, 1)
        self.splitter_7 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.peak_press_label = QtWidgets.QLabel(self.splitter_7)
        self.peak_press_label.setObjectName("peak_press_label")
        self.peak_press_lcd = QtWidgets.QLCDNumber(self.splitter_7)
        self.peak_press_lcd.setObjectName("peak_press_lcd")
        self.gridLayout.addWidget(self.splitter_7, 2, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.bpm_label = QtWidgets.QLabel(self.splitter)
        self.bpm_label.setObjectName("bpm_label")
        self.bpm_lcd = QtWidgets.QLCDNumber(self.splitter)
        self.bpm_lcd.setObjectName("bpm_lcd")
        self.bpm_slider = QtWidgets.QSlider(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bpm_slider.sizePolicy().hasHeightForWidth())
        self.bpm_slider.setSizePolicy(sizePolicy)
        self.bpm_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bpm_slider.setObjectName("bpm_slider")
        self.gridLayout.addWidget(self.splitter, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1067, 22))
        self.menubar.setObjectName("menubar")
        self.menuAqualung = QtWidgets.QMenu(self.menubar)
        self.menuAqualung.setObjectName("menuAqualung")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAqualung.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resp_rate_label.setText(_translate("MainWindow", "Respiratory Rate"))
        self.plateau_press_label.setText(_translate("MainWindow", "Plateau Pressure"))
        self.fio2_label.setText(_translate("MainWindow", "FIO2"))
        self.tv_label.setText(_translate("MainWindow", "Tidal Volume"))
        self.ie_label.setText(_translate("MainWindow", "I/E ratio"))
        self.mode_label.setText(_translate("MainWindow", "Vent. Mode"))
        self.mode_button.setText(_translate("MainWindow", "SIMV"))
        self.peep_label.setText(_translate("MainWindow", "PEEP"))
        self.peak_press_label.setText(_translate("MainWindow", "Peak Insp. Pressure"))
        self.bpm_label.setText(_translate("MainWindow", "BPM"))
        self.menuAqualung.setTitle(_translate("MainWindow", "Oregon Volunteer Ventilator Project"))
