# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 5, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 17, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 15, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 10, 2, 1, 1)
        self.main_tv = QtWidgets.QPushButton(self.main_page)
        self.main_tv.setObjectName("main_tv")
        self.gridLayout_3.addWidget(self.main_tv, 15, 4, 1, 1)
        self.tv_label = QtWidgets.QLabel(self.main_page)
        self.tv_label.setObjectName("tv_label")
        self.gridLayout_3.addWidget(self.tv_label, 15, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 13, 1, 1, 1)
        self.resp_rate_label = QtWidgets.QLabel(self.main_page)
        self.resp_rate_label.setObjectName("resp_rate_label")
        self.gridLayout_3.addWidget(self.resp_rate_label, 17, 0, 1, 1)
        self.resp_rate_main_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.resp_rate_main_lcd.setObjectName("resp_rate_main_lcd")
        self.gridLayout_3.addWidget(self.resp_rate_main_lcd, 17, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 6, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 15, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 17, 1, 1, 1)
        self.ie_main_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.ie_main_lcd.setObjectName("ie_main_lcd")
        self.gridLayout_3.addWidget(self.ie_main_lcd, 13, 2, 1, 1)
        self.peak_press_main_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.peak_press_main_lcd.setObjectName("peak_press_main_lcd")
        self.gridLayout_3.addWidget(self.peak_press_main_lcd, 4, 2, 1, 1)
        self.plat_press_main_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.plat_press_main_lcd.setObjectName("plat_press_main_lcd")
        self.gridLayout_3.addWidget(self.plat_press_main_lcd, 6, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 16, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 5, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 12, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 18, 2, 1, 1)
        self.main_cancel = QtWidgets.QPushButton(self.main_page)
        self.main_cancel.setObjectName("main_cancel")
        self.gridLayout_3.addWidget(self.main_cancel, 20, 0, 1, 6)
        self.mode_label = QtWidgets.QLabel(self.main_page)
        self.mode_label.setObjectName("mode_label")
        self.gridLayout_3.addWidget(self.mode_label, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem16, 1, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem17, 14, 2, 1, 1)
        self.main_apply = QtWidgets.QPushButton(self.main_page)
        self.main_apply.setObjectName("main_apply")
        self.gridLayout_3.addWidget(self.main_apply, 19, 0, 1, 6)
        self.peep_main_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.peep_main_lcd.setObjectName("peep_main_lcd")
        self.gridLayout_3.addWidget(self.peep_main_lcd, 9, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 7, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 9, 1, 1, 1)
        self.main_peep = QtWidgets.QPushButton(self.main_page)
        self.main_peep.setObjectName("main_peep")
        self.gridLayout_3.addWidget(self.main_peep, 9, 4, 1, 1)
        self.main_fio2 = QtWidgets.QPushButton(self.main_page)
        self.main_fio2.setObjectName("main_fio2")
        self.gridLayout_3.addWidget(self.main_fio2, 11, 4, 1, 1)
        self.main_ie = QtWidgets.QPushButton(self.main_page)
        self.main_ie.setObjectName("main_ie")
        self.gridLayout_3.addWidget(self.main_ie, 13, 4, 1, 1)
        self.tv_main_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.tv_main_lcd.setObjectName("tv_main_lcd")
        self.gridLayout_3.addWidget(self.tv_main_lcd, 15, 2, 1, 1)
        self.fio2_label = QtWidgets.QLabel(self.main_page)
        self.fio2_label.setObjectName("fio2_label")
        self.gridLayout_3.addWidget(self.fio2_label, 11, 0, 1, 1)
        self.fio2_lcd = QtWidgets.QLCDNumber(self.main_page)
        self.fio2_lcd.setObjectName("fio2_lcd")
        self.gridLayout_3.addWidget(self.fio2_lcd, 11, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 13, 5, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 11, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 11, 5, 1, 1)
        self.ie_label = QtWidgets.QLabel(self.main_page)
        self.ie_label.setObjectName("ie_label")
        self.gridLayout_3.addWidget(self.ie_label, 13, 0, 1, 1)
        self.plat_press_label = QtWidgets.QLabel(self.main_page)
        self.plat_press_label.setObjectName("plat_press_label")
        self.gridLayout_3.addWidget(self.plat_press_label, 6, 0, 1, 1)
        self.mode_button = QtWidgets.QPushButton(self.main_page)
        self.mode_button.setObjectName("mode_button")
        self.gridLayout_3.addWidget(self.mode_button, 0, 1, 1, 1)
        self.peep_label = QtWidgets.QLabel(self.main_page)
        self.peep_label.setObjectName("peep_label")
        self.gridLayout_3.addWidget(self.peep_label, 9, 0, 1, 1)
        self.main_resp_rate = QtWidgets.QPushButton(self.main_page)
        self.main_resp_rate.setObjectName("main_resp_rate")
        self.gridLayout_3.addWidget(self.main_resp_rate, 17, 4, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 4, 1, 1, 1)
        self.peak_press_label = QtWidgets.QLabel(self.main_page)
        self.peak_press_label.setObjectName("peak_press_label")
        self.gridLayout_3.addWidget(self.peak_press_label, 4, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem24, 9, 5, 1, 1)
        self.stackedWidget.addWidget(self.main_page)
        self.peep = QtWidgets.QWidget()
        self.peep.setObjectName("peep")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.peep)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.peep)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.peep)
        self.fio2 = QtWidgets.QWidget()
        self.fio2.setObjectName("fio2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fio2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fio2_page_apply = QtWidgets.QPushButton(self.fio2)
        self.fio2_page_apply.setObjectName("fio2_page_apply")
        self.gridLayout_5.addWidget(self.fio2_page_apply, 3, 0, 1, 1)
        self.fio2_page_lcd = QtWidgets.QLCDNumber(self.fio2)
        self.fio2_page_lcd.setObjectName("fio2_page_lcd")
        self.gridLayout_5.addWidget(self.fio2_page_lcd, 0, 0, 2, 1)
        self.fio2_page_cancel = QtWidgets.QPushButton(self.fio2)
        self.fio2_page_cancel.setObjectName("fio2_page_cancel")
        self.gridLayout_5.addWidget(self.fio2_page_cancel, 3, 1, 1, 1)
        self.fio2_down = QtWidgets.QPushButton(self.fio2)
        self.fio2_down.setObjectName("fio2_down")
        self.gridLayout_5.addWidget(self.fio2_down, 1, 1, 1, 1)
        self.fio2_up = QtWidgets.QPushButton(self.fio2)
        self.fio2_up.setObjectName("fio2_up")
        self.gridLayout_5.addWidget(self.fio2_up, 0, 1, 1, 1)
        self.fio2_main = QtWidgets.QPushButton(self.fio2)
        self.fio2_main.setObjectName("fio2_main")
        self.gridLayout_5.addWidget(self.fio2_main, 4, 0, 1, 2)
        self.stackedWidget.addWidget(self.fio2)
        self.ie = QtWidgets.QWidget()
        self.ie.setObjectName("ie")
        self.gridLayout = QtWidgets.QGridLayout(self.ie)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.ie)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pg2_1 = QtWidgets.QPushButton(self.ie)
        self.pg2_1.setObjectName("pg2_1")
        self.gridLayout.addWidget(self.pg2_1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.ie)
        self.tv = QtWidgets.QWidget()
        self.tv.setObjectName("tv")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tv)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tv)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.pg3_1 = QtWidgets.QPushButton(self.tv)
        self.pg3_1.setObjectName("pg3_1")
        self.gridLayout_4.addWidget(self.pg3_1, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.tv)
        self.resp_rate = QtWidgets.QWidget()
        self.resp_rate.setObjectName("resp_rate")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.resp_rate)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.resp_rate)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_6.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.resp_rate)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_tv.setText(_translate("MainWindow", "EDIT"))
        self.tv_label.setText(_translate("MainWindow", "Tidal Volume"))
        self.resp_rate_label.setText(_translate("MainWindow", "Resp. Rate"))
        self.main_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.mode_label.setText(_translate("MainWindow", "Mode"))
        self.main_apply.setText(_translate("MainWindow", "APPLY"))
        self.main_peep.setText(_translate("MainWindow", "EDIT"))
        self.main_fio2.setText(_translate("MainWindow", "EDIT"))
        self.main_ie.setText(_translate("MainWindow", "EDIT"))
        self.fio2_label.setText(_translate("MainWindow", "FiO2"))
        self.ie_label.setText(_translate("MainWindow", "IE Ratio"))
        self.plat_press_label.setText(_translate("MainWindow", "Plateau Pressure"))
        self.mode_button.setText(_translate("MainWindow", "SIMV"))
        self.peep_label.setText(_translate("MainWindow", "PEEP"))
        self.main_resp_rate.setText(_translate("MainWindow", "EDIT"))
        self.peak_press_label.setText(_translate("MainWindow", "Peak Inspiratory Pressure"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.fio2_page_apply.setText(_translate("MainWindow", "APPLY CHANGES"))
        self.fio2_page_cancel.setText(_translate("MainWindow", "CANCEL CHANGES"))
        self.fio2_down.setText(_translate("MainWindow", "Decrease FiO2"))
        self.fio2_up.setText(_translate("MainWindow", "Increase FiO2"))
        self.fio2_main.setText(_translate("MainWindow", "Back to Main Menu"))
        self.label.setText(_translate("MainWindow", "This is page 2"))
        self.pg2_1.setText(_translate("MainWindow", "Back to page 1"))
        self.label_2.setText(_translate("MainWindow", "This is page 3"))
        self.pg3_1.setText(_translate("MainWindow", "Back to Page 1"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
